spring:
  application:
    name: action-service    
#  data:
#    mongodb:
#      uri: mongodb://santosh:passw0rd@localhost:27017/flower
#      connection-pool-size: 10
#      driver-class-name: org.mongodb.driver.MongoDriver      
custom:
  properties: qa
      